apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ['sh', '-c', 'ls -la /etc/secrets && cat /etc/secrets/username && sleep 3600']
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: db-credentials
      defaultMode: 0400  # 파일 권한: 소유자만 읽기
      # 특정 키만 마운트
      # items:
      # - key: username
      #   path: db-user
