apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080  # 30000-32767 범위, 생략시 자동 할당
    protocol: TCP
