apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-storage
      mountPath: /usr/share/nginx/html  # nginx 기본 웹 루트

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc  # 사용할 PVC 이름
