apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi  # 제공하는 스토리지 용량
  accessModes:
    - ReadWriteOnce  # 단일 노드에서 읽기/쓰기
  persistentVolumeReclaimPolicy: Retain  # PVC 삭제 시 PV 유지
  storageClassName: manual  # PVC와 매칭하기 위한 클래스명
  hostPath:
    path: /mnt/data  # 실제 노드의 디렉토리 경로
    type: DirectoryOrCreate  # 없으면 생성
